[[entity]]

    [entity.components.Text]
    id = "life"
    text = "LIVES: 3"
    font_face = { font = "joystix", options = { size = 25.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 990, y = 790 }
    pivot = "TopRight"
