[[entity]]

    [entity.components.Text]
    id = "title"
    text = "Space invaders"
    font_face = { font = "joystix", options = { size = 75.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 650 }


[[entity]]

    [entity.components.Text]
    id = "cursor_new_game"
    text = "\u25ba"
    font_face = { font = "hack", options = { size = 60.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 230, y = 400 }


[[entity]]

    [entity.components.Text]
    id = "cursor_exit"
    text = "\u25ba"
    font_face = { font = "hack", options = { size = 60.0, hinting = "Full" } }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 330, y = 250 }


[[entity]]

    [entity.components.Text]
    id = "new_game"
    text = "NEW GAME"
    font_face = { font = "joystix", options = { size = 60.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 400 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 420, height = 60 }

    [entity.components.Transform]
    translation = { x = 500.0, y = 400.0 }

    [entity.components.MouseReactive]
    id = "new_game"


[[entity]]

    [entity.components.Text]
    id = "exit"
    text = "EXIT"
    font_face = { font = "joystix", options = { size = 60.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 250 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 220, height = 60 }

    [entity.components.Transform]
    translation = { x = 500.0, y = 250.0 }

    [entity.components.MouseReactive]
    id = "exit"
